"""
nmap_scanner.py
Implements Step 3 of the algorithm: Service and port enumeration using Nmap.
"""

import subprocess # Imports the module used to run system commands.
from pathlib import Path  # Imports the tool used to manage file paths safely on any operating system.

# Set the save location for assessment files.
OUTPUT_DIRECTORY = Path("outputs")

def scan_host(ip):
    """
    Performs service enumeration against one discovered laboratory host.
    """
    # Create the evidence directory if it does not already exist.
    OUTPUT_DIRECTORY.mkdir(
        exist_ok=True
    )

    # Replace dots in the IP address so that the filename is clean and easy to read.
    output_file = (
        OUTPUT_DIRECTORY /
        f"nmap_{ip.replace('.', '_')}"
    )

    # Construct the Nmap command.
    # -p-  = examine all 65,535 TCP ports
    # -sV  = identify service/version information
    # -sC  = run Nmap's standard security scripts
    # -oA  = save results in 3 formats (.nmap, .xml, .gnmap) automatically
    command = [
        "nmap",
        "-p-",
        "-sV",
        "-sC",
        str(ip),
        "-oA",
        str(output_file)
    ]

    # Execute Nmap and raise an error if the process fails.
    subprocess.run(
        command,
        check=True
    )

    # Locate and read the standard text (.nmap) format file generated by -oA.
    nmap_file = Path(f"{output_file}.nmap")

    if nmap_file.exists():
        return nmap_file.read_text(
            encoding="utf-8"
        )

    # Return an empty string if the file was not generated.
    return ""



